// Generated by FlutterFire CLI after you run:
//   flutterfire configure --project=YOUR_PROJECT --platforms=android
// Until then the app runs in mock/demo mode (USE_MOCK=true by default).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  DefaultFirebaseOptions._();

  static const bool configured = bool.fromEnvironment(
    'FIREBASE_CONFIGURED',
    defaultValue: false,
  );

  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase is not configured. Run flutterfire configure --platforms=android '
      'or keep using mock mode (default).',
    );
  }
}
